version: "3.9"

services:
  axolstores:
    build: .
    container_name: axolstores
    restart: unless-stopped
    networks:
      - axol-network
    environment:
      NODE_ENV: production
      PORT: 3000
    expose:
      - "3000"

networks:
  axol-network:
    external: true